class cuboSemantico:
	def _init_(self):
		self.table =
		{
			('int', 'int', '+'): 'int',
            ('int', 'int', '-'): 'int',
            ('int', 'int', '*'): 'int',
            ('int', 'int', '/'): 'int',
            ('int', 'int', '<'): 'bool',
            ('int', 'int', '<='): 'bool',
            ('int', 'int', '>'): 'bool',
            ('int', 'int', '>='): 'bool',
            ('int', 'int', '='): 'int',
            ('int', 'int', '=='): 'bool',
            ('int', 'int', '<>'): 'bool',
            ('int', 'int', '&&'): "Type mismatch",
            ('int', 'int', '||'): "Type mismatch",

            ('int', 'float', '+'): 'float',
            ('int', 'float', '-'): 'float',
            ('int', 'float', '*'): 'float',
            ('int', 'float', '/'): 'float',
            ('int', 'float', '<'): 'bool',
            ('int', 'float', '<='): 'bool',
            ('int', 'float', '>'): 'bool',
            ('int', 'float', '>='): 'bool',
            ('int', 'float', '='): 'int',
            ('int', 'float', '=='): 'bool',
            ('int', 'float', '<>'): 'bool',
            ('int', 'float', '&&'): "Type mismatch",
            ('int', 'float', '||'): "Type mismatch",

            ('int', 'char', '+'): "Type mismatch",
            ('int', 'char', '-'): "Type mismatch",
            ('int', 'char', '*'): "Type mismatch",
            ('int', 'char', '/'): "Type mismatch",
            ('int', 'char', '<'): "Type mismatch",
            ('int', 'char', '<='): "Type mismatch",
            ('int', 'char', '>'): "Type mismatch",
            ('int', 'char', '>='): "Type mismatch",
            ('int', 'char', '='): "Type mismatch",
            ('int', 'char', '=='): "Type mismatch",
            ('int', 'char', '<>'): "Type mismatch",
            ('int', 'char', '&&'): "Type mismatch",
            ('int', 'char', '||'): "Type mismatch",

            ('int', 'bool', '+'): "Type mismatch",
            ('int', 'bool', '-'): "Type mismatch",
            ('int', 'bool', '*'): "Type mismatch",
            ('int', 'bool', '/'): "Type mismatch",
            ('int', 'bool', '<'): "Type mismatch",
            ('int', 'bool', '<='): "Type mismatch",
            ('int', 'bool', '>'): "Type mismatch",
            ('int', 'bool', '>='): "Type mismatch",
            ('int', 'bool', '='): "Type mismatch",
            ('int', 'bool', '=='): "Type mismatch",
            ('int', 'bool', '<>'): "Type mismatch",
            ('int', 'bool', '&&'): "Type mismatch",
            ('int', 'bool', '||'): "Type mismatch",

            ('float', 'int', '+'): 'float',
            ('float', 'int', '-'): 'float',
            ('float', 'int', '*'): 'float',
            ('float', 'int', '/'): 'float',
            ('float', 'int', '<'): 'bool',
            ('float', 'int', '<='): 'bool',
            ('float', 'int', '>'): 'bool',
            ('float', 'int', '>='): 'bool',
            ('float', 'int', '='): 'float',
            ('float', 'int', '=='): 'bool',
            ('float', 'int', '<>'): 'bool',
            ('float', 'int', '&&'): "Type mismatch",
            ('float', 'int', '||'): "Type mismatch",

            ('float', 'float', '+'): 'float',
            ('float', 'float', '-'): 'float',
            ('float', 'float', '*'): 'float',
            ('float', 'float', '/'): 'float',
            ('float', 'float', '<'): 'bool',
            ('float', 'float', '<='): 'bool',
            ('float', 'float', '>'): 'bool',
            ('float', 'float', '>='): 'bool',
            ('float', 'float', '='): 'float',
            ('float', 'float', '=='): 'bool',
            ('float', 'float', '<>'): 'bool',
            ('float', 'float', '&&'): "Type mismatch",
            ('float', 'float', '||'): "Type mismatch",

            ('float', 'char', '+'): "Type mismatch",
            ('float', 'char', '-'): "Type mismatch",
            ('float', 'char', '*'): "Type mismatch",
            ('float', 'char', '/'): "Type mismatch",
            ('float', 'char', '<'): "Type mismatch",
            ('float', 'char', '<='): "Type mismatch",
            ('float', 'char', '>'): "Type mismatch",
            ('float', 'char', '>='): "Type mismatch",
            ('float', 'char', '='): "Type mismatch",
            ('float', 'char', '=='): "Type mismatch",
            ('float', 'char', '<>'): "Type mismatch",
            ('float', 'char', '&&'): "Type mismatch",
            ('float', 'char', '||'): "Type mismatch",

            ('float', 'bool', '+'): "Type mismatch",
            ('float', 'bool', '-'): "Type mismatch",
            ('float', 'bool', '*'): "Type mismatch",
            ('float', 'bool', '/'): "Type mismatch",
            ('float', 'bool', '<'): "Type mismatch",
            ('float', 'bool', '<='): "Type mismatch",
            ('float', 'bool', '>'): "Type mismatch",
            ('float', 'bool', '>='): "Type mismatch",
            ('float', 'bool', '='): "Type mismatch",
            ('float', 'bool', '=='): "Type mismatch",
            ('float', 'bool', '<>'): "Type mismatch",
            ('float', 'bool', '&&'): "Type mismatch",
            ('float', 'bool', '||'): "Type mismatch",

            ('char', 'int', '+'): "Type mismatch",
            ('char', 'int', '-'): "Type mismatch",
            ('char', 'int', '*'): "Type mismatch",
            ('char', 'int', '/'): "Type mismatch",
            ('char', 'int', '<'): "Type mismatch",
            ('char', 'int', '<='): "Type mismatch",
            ('char', 'int', '>'): "Type mismatch",
            ('char', 'int', '>='): "Type mismatch",
            ('char', 'int', '='): "Type mismatch",
            ('char', 'int', '=='): "Type mismatch",
            ('char', 'int', '<>'): "Type mismatch",
            ('char', 'int', '&&'): "Type mismatch",
            ('char', 'int', '||'): "Type mismatch",

            ('char', 'float', '+'): "Type mismatch",
            ('char', 'float', '-'): "Type mismatch",
            ('char', 'float', '*'): "Type mismatch",
            ('char', 'float', '/'): "Type mismatch",
            ('char', 'float', '<'): "Type mismatch",
            ('char', 'float', '<='): "Type mismatch",
            ('char', 'float', '>'): "Type mismatch",
            ('char', 'float', '>='): "Type mismatch",
            ('char', 'float', '='): "Type mismatch",
            ('char', 'float', '=='): "Type mismatch",
            ('char', 'float', '<>'): "Type mismatch",
            ('char', 'float', '&&'): "Type mismatch",
            ('char', 'float', '||'): "Type mismatch",

            ('char', 'char', '+'): "Type mismatch",
            ('char', 'char', '-'): "Type mismatch",
            ('char', 'char', '*'): "Type mismatch",
            ('char', 'char', '/'): "Type mismatch",
            ('char', 'char', '<'): "Type mismatch",
            ('char', 'char', '<='): "Type mismatch",
            ('char', 'char', '>'): "Type mismatch",
            ('char', 'char', '>='): "Type mismatch",
            ('char', 'char', '='): 'char',
            ('char', 'char', '=='): 'bool',
            ('char', 'char', '<>'): 'bool',
            ('char', 'char', '&&'): "Type mismatch",
            ('char', 'char', '||'): "Type mismatch",

            ('char', 'bool', '+'): "Type mismatch",
            ('char', 'bool', '-'): "Type mismatch",
            ('char', 'bool', '*'): "Type mismatch",
            ('char', 'bool', '/'): "Type mismatch",
            ('char', 'bool', '<'): "Type mismatch",
            ('char', 'bool', '<='): "Type mismatch",
            ('char', 'bool', '>'): "Type mismatch",
            ('char', 'bool', '>='): "Type mismatch",
            ('char', 'bool', '='): "Type mismatch",
            ('char', 'bool', '=='): "Type mismatch",
            ('char', 'bool', '<>'): "Type mismatch",
            ('char', 'bool', '&&'): "Type mismatch",
            ('char', 'bool', '||'): "Type mismatch",

            ('bool', 'int', '+'): "Type mismatch",
            ('bool', 'int', '-'): "Type mismatch",
            ('bool', 'int', '*'): "Type mismatch",
            ('bool', 'int', '/'): "Type mismatch",
            ('bool', 'int', '<'): "Type mismatch",
            ('bool', 'int', '<='): "Type mismatch",
            ('bool', 'int', '>'): "Type mismatch",
            ('bool', 'int', '>='): "Type mismatch",
            ('bool', 'int', '='): "Type mismatch",
            ('bool', 'int', '=='): "Type mismatch",
            ('bool', 'int', '<>'): "Type mismatch",
            ('bool', 'int', '&&'): "Type mismatch",
            ('bool', 'int', '||'): "Type mismatch",

            ('bool', 'float', '+'): "Type mismatch",
            ('bool', 'float', '-'): "Type mismatch",
            ('bool', 'float', '*'): "Type mismatch",
            ('bool', 'float', '/'): "Type mismatch",
            ('bool', 'float', '<'): "Type mismatch",
            ('bool', 'float', '<='): "Type mismatch",
            ('bool', 'float', '>'): "Type mismatch",
            ('bool', 'float', '>='): "Type mismatch",
            ('bool', 'float', '='): "Type mismatch",
            ('bool', 'float', '=='): "Type mismatch",
            ('bool', 'float', '<>'): "Type mismatch",
            ('bool', 'float', '&&'): "Type mismatch",
            ('bool', 'float', '||'): "Type mismatch",

            ('bool', 'char', '+'): "Type mismatch",
            ('bool', 'char', '-'): "Type mismatch",
            ('bool', 'char', '*'): "Type mismatch",
            ('bool', 'char', '/'): "Type mismatch",
            ('bool', 'char', '<'): "Type mismatch",
            ('bool', 'char', '<='): "Type mismatch",
            ('bool', 'char', '>'): "Type mismatch",
            ('bool', 'char', '>='): "Type mismatch",
            ('bool', 'char', '='): "Type mismatch",
            ('bool', 'char', '=='): "Type mismatch",
            ('bool', 'char', '<>'): "Type mismatch",
            ('bool', 'char', '&&'): "Type mismatch",
            ('bool', 'char', '||'): "Type mismatch",

            ('bool', 'bool', '+'): "Type mismatch",
            ('bool', 'bool', '-'): "Type mismatch",
            ('bool', 'bool', '*'): "Type mismatch",
            ('bool', 'bool', '/'): "Type mismatch",
            ('bool', 'bool', '<'): "Type mismatch",
            ('bool', 'bool', '<='): "Type mismatch",
            ('bool', 'bool', '>'): "Type mismatch",
            ('bool', 'bool', '>='): "Type mismatch",
            ('bool', 'bool', '='): 'bool',
            ('bool', 'bool', '=='): 'bool',
            ('bool', 'bool', '<>'): 'bool',
            ('bool', 'bool', '&&'): 'bool',
            ('bool', 'bool', '||'): 'bool'
		}
